server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate.dll-auto: create
    generate-ddl: false
  flyway:
    locations:
      - db/migration
      - db/seed
  data:
    mongodb:
      host: localhost
      port: 27017
      database: db
